In [1]:
print("hello")

hello


In [2]:
x =10
if(x>20):
    print("x is greater than 20")
elif(x==20):
    print("x equal to 20")
else:
    print("x is less than 20")

x is less than 20


In [1]:
a= ["Apple","Banana","Strabery"]
for i in a:
    print(i)

Apple
Banana
Strabery


In [2]:
def function():
    a =0
    print(a)
function()

0


In [13]:
x = 10
def fun():
    x =20 #local variable so it will not change the value of x
    print(x)
    global x
    x = x+10
    print(x)

SyntaxError: name 'x' is used prior to global declaration (1501732648.py, line 5)

In [14]:
x = 10
def fun():
    global x
    x = x+10
    print(x)
    x =20 #local variable so it will not change the value of x
    print(x)

In [15]:
fun()

20
20


In [ ]:

def fun():


In [45]:
import string
str1 = "The quick brown or sentences containing every letter of the alphabet at least once"
str2 = "abcdefghijklmnopqrstuvwxyz"
str3 = set(str1.lower())
str3.remove(' ')

str2
string.ascii_lowercase

True


'abcdefghijklmnopqrstuvwxyz'

In [ ]:
import string
a = string.ascii_lowercase
str1 = "The quick brown or sentences containing every letter of the alphabet at least once"
c= set(a.lower)


In [47]:
a= int(input("Enter the first number"))
b = int(input("Enter the second number"))
for i in range(a,b+1):
    if(i%2 != 0 and i%9 != 0 and i%11 != 0):
        print(i)

1
3
5
7
9


In [63]:
import numpy as np

# np.mean([1,2,3])
np.median([1,2,3,4])

2.5

In [4]:
import numpy as np
cric_data = np.loadtxt("https://raw.githubusercontent.com/goradbj/MachineLearning/main/cric.tsv",skiprows=1)
cric_data







array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [6]:
Sachin = cric_data[:,1]
print(Sachin)
np.mean(Sachin)

[100.  11.   8.  71. 104.  18.   8.  86.  12.  25.  56.  88. 147. 121.
  99.]


63.6

In [ ]:
Sachin = cric_data[:,1]
np.median(Sachin)

In [ ]:
Dravid = cric_data[:,2]
np.median(Dravid)

In [ ]:
Dravid = cric_data[:,2]
np.mean(Dravid)

HomeWork Question Solved !!!!!

In [1]:
a = [8,7,1,5,6,32]
max =0
second_max = 0
index_of_max = 0
b = []
for i in range(len(a)):
    if(a[i]>max):
        max = a[i]
        index_of_max = i
for i in range(len(a)):
    if(a[i]>second_max and a[i]<max):
        second_max = a[i]

first_half = a[:index_of_max]
second_half = a[index_of_max+1:]
first_half.append(second_max)
first_half.append(max-second_max)
first_half.extend(second_half)
print(first_half)
print(a)
        



[8, 7, 1, 5, 6, 8, 24]
[8, 7, 1, 5, 6, 32]


In [29]:
from numpy import random
random.seed()
x= random.randint(1,11)
print(x)

3


In [59]:
from numpy import random
random.seed(9)
x = random.randint(10,size=(1,5,5))
#how many index you have to pass to access element
print(x[0][1][0])
print(x)
int_arr = np.array([8,9])
print(int_arr)

6
[[[5 6 8 6 1]
  [6 4 8 1 8]
  [5 1 0 8 8]
  [8 2 6 8 1]
  [8 3 5 3 6]]]
[8 9]


In [50]:


import numpy as np

in_arr = np.array([8])

print("input array is ", in_arr)

out_scalar = np.asscalar(in_arr)
print("output scalar from input array ", out_scalar)

input array is  [8]
output scalar from input array  8


C:\Users\Raj Kaneriya\AppData\Local\Temp\ipykernel_42168\3009928484.py:7: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar = np.asscalar(in_arr)


In [55]:
import numpy as np

#creating 1-D list
list1 = [1, 2, 3]

#creating 1-D list vertical

list2 = [[10],
        [20],
        [30]]

list3  =[[10],[20],[30]]

#create vector1

vector1 =  np.array(list1)
vector2 = np.array(list2)

print("Horizontal Vector")
print(vector1)

print("------------------")

print("Vertical Vector")
print(vector2)

type(vector1)
vector1.ndim

Horizontal Vector
[1 2 3]
------------------
Vertical Vector
[[10]
 [20]
 [30]]


1

In [56]:
vector3 = np.array(list3)
vector3.ndim

2

In [60]:
import numpy as np

a=np.matrix('1 2; 3 4') #how to pads 3d
print("via string input : \n", a, "\n\n")

#array-like input
b = np.matrix([[5, 6], [3,4],[1,2]])
print("via array-like input :\n", b)

via string input : 
 [[1 2]
 [3 4]] 


via array-like input :
 [[5 6]
 [3 4]
 [1 2]]


In [62]:
import numpy as np

A = np.matrix([[5, 6], 
                [3,4],
                [1,2]])
B = np.matrix([[5, 6],
                [3,4]])

print(np.dot(A,B))

[[43 54]
 [27 34]
 [11 14]]


Array multiplication multiply with number to number not like matrix we can't use in list to multyply list 

In [63]:
a = np.array([[1,2] , [2,4]])
b = np.array([[1,2] , [2,4]])

a*b

array([[ 1,  4],
       [ 4, 16]])

In [64]:
import numpy as np

arr = np.array([[[1,23,78]], [[98,60,75]],[[79,25,48]]])
print(arr)

#min function
print(np.amin(arr))
#max function
print(np.amax(arr))

[[[ 1 23 78]]

 [[98 60 75]]

 [[79 25 48]]]
1
98
